Lesson 8 szilard vig
mariuspodean/POCU-PD-01 pull request #13
Opened 2020-07-02 18:25 UTC by vigsz

2020-07-09 06:36 UTC, Liitle requested changes
Great job. Just one thing, please remove the vscode config files from the commit, see the comment below

2020-07-09 06:36 UTC, Liitle commented on .vscode/launch.json
> +{
You can add `.vscode` to `.gitignore` file. By doing so git will stop tracking the vscode config files 

To remove the config files from this commit try this: 

https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

I can also help with this, if it becomes to complicated 😄

2020-07-10 20:22 UTC, vigsz commented
Removed vscode config files from commit. Please review again.

2020-07-12 19:28 UTC, Liitle approved these changes

2020-07-12 19:28 UTC, merged